### ISSUE TITLE
max_execution_time does not get go beyond 30 seconds

### ISSUE THREAD

**Issue by Jan-Barrera** [ContentSquare/chproxy#150]
Hi, 

I have a client that connects to Clickhouse using jdbc and I have a long running query that takes over 40 seconds when using the Clickhouse server endpoint.

When using chproxy however, chproxy tries to kill the query at 30 seconds (it gets an authentication error trying to kill the query hence the log). 
`ERROR: 2022/03/16 03:31:51 proxy.go:201: [ Id: 16DCBEE8C5562CE5; User "default"(1) proxying as "default"(1) to "10.xx.xx.xx:8123"(1); RemoteAddr: "10.xx.xx.xx:50674"; LocalAddr: "10.xx.xx.xx:9090"; Duration: 30007377 μs]: cannot kill query`

I set the max_execution_time to 400 seconds but it still tries to kill the query at 30 seconds. 
`ERROR: 2022/03/16 03:40:33 proxy.go:201: [ Id: 16DCBF4EC9A5C91F; User "default"(1) proxying as "default"(1) to "10.xx.xx.xx:8123"(1); RemoteAddr: "10.xx.xx.xx:50848"; LocalAddr: "10.xx.xx.xx:9090"; Duration: 31078772 μs]: cannot kill query`

Just to verify, i tried setting the max execution time to 10 seconds, and it kills the query at 10 seconds. 
`ERROR: 2022/03/16 03:37:49 proxy.go:214: [ Id: 16DCBF408125FCF2; User "default"(1) proxying as "default"(1) to "10.xx.xx.xx:8123"(1); RemoteAddr: "10.xx.xx.xx:50812"; LocalAddr: "10.xx.xx.xx:9090"; Duration: 10001026 μs]: cannot kill query`

But setting it beyond 30 seconds has no effect. It still tries to kill the query at 30 seconds. 

Note that I get successful results when querying directly to clickhouse and only getting this error when querying via chproxy. 

I am using chproxy v1.14.0 and clickhouse-jdbc v0.3.2 
query string:
`jdbc:clickhouse://10.xx.xx.xx:9090??socket_timeout=300000`

config:
```
hack_me_please: false
server:
  http:
    listen_addr: ':9090'
    allowed_networks:
      - 10.xx.xx.xx/xx
    read_timeout: 20m
    write_timeout: 20m
    idle_timeout: 20m
users:
  - name: default
    password: xxx
    to_cluster: test_cluster
    to_user: default
    allow_cors: true
    max_execution_time: 400s
clusters:
  - name: test_cluster
    nodes:
      - '10.xx.xx.xx:8123'
    users:
      - name: default
        password: xxxx
```

Please advise. 

Thanks!
