### ISSUE TITLE
SIGHUP does not refresh TLS certificate

### ISSUE THREAD

**Issue by paulchoi** [ContentSquare/chproxy#198]
Should issuing SIGHUP to chproxy cause it to reload the TLS certificate? 
The TLS cert served by chproxy is still the old one.

I am not using letsencrypt, but my infrastructure is able to provide short-lived TLS certificates that refresh every week.

```
server:
  http:
    listen_addr: ":9090"
  https:
    listen_addr: ":443"
    cert_file: /config/chain.pem
    key_file: /config/private.pem
```
