### ISSUE TITLE
use wildcarded users with different name and to_user values  

### ISSUE THREAD

**Issue by liadt-neosec** [ContentSquare/chproxy#263]
Hi,
I have been trying to implement a wildcarded configuration, but where the name is different from to_user.

here's an example, where I want any test_tenant_* user to use my_cluster_* users, which does not seem to work for me:
 ```
 users:
 # my tenant user - works fine
  - name: test_tenant
    password: test_tenant
    to_cluster: my_cluster
    to_user: test_tenant
    is_wildcarded: false
 # wildcarded user - doesn't work
 - name:  test_tenant_*
    to_cluster: my_cluster
    to_user:  my_cluster_*
    is_wildcarded: true

clusters:
  - name: "my_cluster"
    scheme: "http"
    nodes: ["0.0.0.0:8123"]
    users:
      - name:test_tenant
        password: test_tenant
      - name: test_tenant_*
 ```
 
is this suppose to work this way? did I find a bug, or is that suppose to be a feature request?

thx! :)
