### ISSUE TITLE
[BUG] Missing metric concurrent_limit_excess_total

### ISSUE THREAD

**Issue by francescsanjuanmrf** [ContentSquare/chproxy#273]
**Describe the bug**
We are making more queries than `max_concurrent_queries` to the same cluster with a same user and the metric `concurrent_limit_excess_total` is never reported in the metrics endpoint.

**To Reproduce**
Set `max_concurrent_queries` to 1 in one cluster's user and make several concurrent queries to the cluster with the user configured.

**Expected behavior**
We expect to see the metric reported in the metrics endpoint.

**Environment information**
We are running chproxy in a kubernetes environment, using the docker image `contentsquareplatform/chproxy:v1.19.0`

**Comment by mga-chka** [comment]
Look weird indeed, after a quick check of the code, I don't see why it doesn't work.
In your tests, are the concurrent queries failing with http code 429 (StatusTooManyRequests)?

**Comment by mga-chka** [comment]
FYI I wasn't able to reproduced your issue using master (btw 1.19.0 and 1.20.0)
In this example I run 2 queries that takes 1 sec at the same time using the following config
```yaml
log_debug: true
hack_me_please: true

users:
  - name: user
    password: pwd
    to_cluster: local
    to_user: default
    max_concurrent_queries: 1
    max_execution_time: 30s

clusters:
  - name: local
    scheme: http
    nodes:
      - 127.0.0.1:8123
    users:
      - name: default
    #heartbeat_interval: 5s
server:
  http:
      listen_addr: ":9090"
      allowed_networks: ["127.0.0.0/24"]

``` 
I first check the metric is at 0
```bash
~/code/chproxy$ curl "http://user:pwd@localhost:9090/metrics" | grep concurrent_limit_excess_total
[no result]
```
then I run the 2 queries in concurrence
```bash
curl  "http://user:pwd@localhost:9090?query=SELECT%20toString(number)%20from%20system.numbers%20limit%20100000000" > file1.tmp & \
curl "http://user:pwd@localhost:9090?query=SELECT%20toString(number)%20from%20system.numbers%20limit%20100000001" > file2.tmp
```
one fails because of `limits for user "user" are exceeded: max_concurrent_queries limit: 1` while the other succeed

and the metric is increased
```bash
~/code/chproxy$ curl -s "http://user:pwd@localhost:9090/metrics" | grep concurrent_limit_excess_total
# HELP concurrent_limit_excess_total Total number of max_concurrent_queries excess
# TYPE concurrent_limit_excess_total counter
concurrent_limit_excess_total{cluster="local",cluster_node="127.0.0.1:8123",cluster_user="default",replica="default",user="user"} 1
```


So can you describe exactly what you did?
