### ISSUE TITLE
Use Chproxy as a data source

### ISSUE THREAD

**Issue by Pavlo9999** [ContentSquare/chproxy#279]
Hello, could Chproxy be used as the data source? 
I am trying to connect Chproxy as a data source to Redash. Redash the system for executing queries and build dashboards with results. 

I have configured a simple Chproxy config file:
```
server:
  http:
    listen_addr: :9090
    allowed_networks:
    - my_external_redash_ip/32
    forceautocerthandler: false
    read_timeout: 1m
    write_timeout: 2m
    idle_timeout: 10m
clusters:
- name: admin
  scheme: http
  nodes:
  - 0.0.0.0:8123
  users:
  - name: my_user
    password: "my_password"
  heartbeat:
    interval: 5s
    timeout: 3s
    request: /?query=SELECT%201
    response: |
      1
users:
- name: default
  to_cluster: admin
  to_user: my_user
  max_concurrent_queries: 6
  max_execution_time: 1m
log_debug: true

```
So when I use curl I get the result 
![image](https://user-images.githubusercontent.com/33752651/207294843-dfc3c2f7-a289-491d-889e-5a51f148f14e.png)

but when I try to connect Chproxy as a data source I get the error:

![image](https://user-images.githubusercontent.com/33752651/207295275-e653f075-4d2f-494a-91f4-7357ae4a4e29.png)

the same in the console:
`ERROR: 2022/12/13 10:35:38 proxy.go:70: "my_ip:50866": invalid username or password for user "my_user"; query: "SELECT 1\nFORMAT JSON"`

So it's some connections or config issue or I can't use Chproxy as a data source because every connect should be with some query?
