### ISSUE TITLE
[attempt to complete transaction] entry not found for key

### ISSUE THREAD

**Issue by woozhijun** [ContentSquare/chproxy#280]
Report an error by viewing the log:
`ERROR: 2022/12/15 06:10:21 transaction_registry_inmem.go:80: [attempt to complete transaction] entry not found for key: 522a4cae58031153f199bb4b0e2d5854, registering new entry with 1 status`

Look code:
<img width="778" alt="image" src="https://user-images.githubusercontent.com/5228147/207796186-04cfc6cc-49f9-44e6-9bda-ce226e7bdb9e.png">

version:
1.19.0

key configuration:
```
 parms:
    - key: "max_execution_time"
       value: "1800"

  - name: "shortterm"
    mode: "file_system"
    file_system:
      dir: "/data3/chproxy/shortterm/cachedir"
      max_size: 30Gb
    expire: 1800s
    grace_time: 120s
```

And,  Not sure where the problem is.
