### ISSUE TITLE
[Feature] Include -config parameter in Dockerfile's entrypoint

### ISSUE THREAD

**Issue by yohannjCS** [ContentSquare/chproxy#305]
**Is your feature request related to a problem? Please describe.**
Trying to use the docker image with docker-compose I did:
```yaml
chproxy:
  image: contentsquareplatform/chproxy:v1.21.0
  ports:
    - 9090:9090
  restart: always
  volumes:
    - ./resources/chproxy/config.yml:/opt/config.yml
  depends_on:
    clickhouse:
      condition: service_healthy
  healthcheck:
    test: "curl http://localhost:9090/metrics"
    interval: 2s
    timeout: 5s
    retries: 10
```

In the logs I get:
```
Usage of /chproxy:
  -config string
    	Proxy configuration filename
  -enableTCP6
    	Whether to enable listening for IPv6 TCP ports. By default only IPv4 TCP ports are listened
  -version
    	Prints current version and exits
```

This is because launching chproxy requires the argument: `-config /config.yml` which is not provided by the docker image built here.

**Describe the solution you'd like**
Update the entrypoint in Dockerfile from `ENTRYPOINT ["/chproxy"]` to `ENTRYPOINT ["/chproxy", "-config", "/config.yml"]`

**Describe alternatives you've considered**
Creating my own Dockerfile on top of the one provided by chproxy, and instead of specifying an image in docker-compose, use:
```yaml
build:
  context: ./chproxy
  dockerfile: Dockerfile
```

Another alternative is to use https://hub.docker.com/r/tacyuuhon/clickhouse-chproxy

**Additional context**
I'm ready to do the PR if this feature is wanted.
