### ISSUE TITLE
[QUESTION] CHProxy caching (v1.19.0)

### ISSUE THREAD

**Issue by Tarkerro** [ContentSquare/chproxy#329]
We used articles to set up local caching
https://www.chproxy.org/configuration/caching
https://github.com/ContentSquare/chproxy/blob/master/config/README.md

**It appears to be active now**
![image_2023-04-24_14-44-38](https://user-images.githubusercontent.com/43171268/233974838-0a8a2a31-0312-4ceb-ba4f-b217acbeb4cb.png)
**However all requests from chproxy still ignore caching and go directly to the clickhouse.**
![image](https://user-images.githubusercontent.com/43171268/233975021-3f09629f-de98-45d4-8c5d-aee9a0efcf31.png)
![image](https://user-images.githubusercontent.com/43171268/233975096-c90f92a4-53ef-4467-b4cd-d2b828a046ae.png)
![image](https://user-images.githubusercontent.com/43171268/233975366-18c57107-fd36-4c3a-b15a-34c092bd743d.png)

**Tried different configurations, the last one:**

```
caches:
  - name: "portfolio_cache"
    mode: "file_system"
    file_system:
      dir: "/opt/chproxy/cache"
      max_size: 50Gb
      max_payload_size: 50Gb
    expire: 1h
    grace_time: 20s
    shared_with_all_users: true
```
    
What could be the problem? Maybe we need additional parameters in the requests, or maybe we 
have a configuration problem?

**Comment by mga-chka** [comment]
I don't know where the problem is but in case it helps, there is a tutorial [here](https://www.chproxy.org/getting_started) that shows how to use chproxy with cache. Can you check it to see if you spot the issue?

**Comment by Blokje5** [comment]
Did you associate the cache with the user? That could be a potential source of issues.

**Comment by Tarkerro** [comment]
Thanks for answers. Yes, the user was associated with the cache by name

With this settings it works perfectly fine:
```
caches:
  - name: "portfolio_cache"
    mode: "file_system"
    file_system:
      dir: "/opt/chproxy_1.19/cache"
      max_size: 20Gb
      max_payload_size: 20Gb
    expire: 1h
    grace_time: 1m
    
    ...
    
  users:
     max_execution_time: 1m
     cache: "portfolio_cache"
```

It looks like shared_with_all_users has only been added since version 1.20.х
We also set the grace_time equal to the max_execution_time.
