### ISSUE TITLE
[BUG] Redis password gets exposed in info logs when redis username is empty

### ISSUE THREAD

**Issue by smunukutla-mycarrier** [ContentSquare/chproxy#398]
**Describe the bug**
Redis password gets exposed in info logs when Redis username is an empty string in Chproxy config.

**To Reproduce**
In a case where we do not provide a Redis username and leave Caches.Redis.Username empty. Leaving username as empty string exposes the Redis password in the info logs. 

Example config to reproduce the scenario:

```
caches:
  - name: "shortterm"
    mode: "redis"
    redis: 
      insecure_skip_verify: true
      addresses: 
        - "somewhere-redis-master:6379"
      username: ""
      password: ${REDIS_PASSWORD}
    expire: 5m
    grace_time: 20s
```

**Expected behavior**
Redis password should be masked as XXX in the info logs. Screenshots added below.

**Screenshots**
Current behavior:
Snippet from info logs:

<img width="400" alt="image" src="https://github.com/ContentSquare/chproxy/assets/149697415/47a735e5-99e2-4d1a-b225-fe8dee47551b"> </img>

</br>
Expected behavior:
</br>
<img width="400" alt="image" src="https://github.com/ContentSquare/chproxy/assets/149697415/a0294db3-7c33-455a-863d-e10cf1b578d9"></img>

**Environment information**
OS: Linux/Amd64
Chproxy: v1.26.0

**Additional context**
None
