### ISSUE TITLE
[QUESTION] Possible unexpected behavior in cacheSize/cacheItems metrics

### ISSUE THREAD

**Issue by hulk8** [ContentSquare/chproxy#461]
**Question details**
I have an original Grafana [dashboard](https://github.com/ContentSquare/chproxy/blob/master/chproxy_overview.json) for chproxy and faced issue with current cache size and cache items metrics.
In my configuration there is a `expire: 15m` and `max_size: 200Gb` configs but on the dashboard and in metrics gauge values [cacheItems](https://github.com/ContentSquare/chproxy/blob/master/metrics.go#L26) and [cacheSize](https://github.com/ContentSquare/chproxy/blob/master/metrics.go#L25) are keep increasing. As I know, gauge can go up and down.
![image](https://github.com/user-attachments/assets/3968c0e9-81eb-439e-9096-d7d0cb6fc78a)

Cache config:
```yml
caches:
  - name: "shortterm"
    mode: "file_system"
    file_system:
      dir: "/app/chproxy/shortterm/cache"
      max_size: 200Gb
    expire: 15m
    shared_with_all_users: true
```
Is this is an expected behavior? Does chproxy clear cache files only when `max_size` is reached?
